### ISSUE TITLE
general bug?

### ISSUE THREAD

**Issue by jwexus** [zWolfrost/Better-Volume-Booster#7]
there seems to be a general bug with firefox sound boosters that videos wont play for some reason on sites. would it be hard to add exclude sites? i have confirmed that the bug happens with sound boosters with disabling all extentions and only replicated on sound boosters including this one! thank you for taking your time to make this btw.

**Comment by zWolfrost** [comment]
It wouldn't be hard to exclude some sites, but I think it would be pretty cumbersome to manually exclude them one by one.

As a workaround, you can try to go in the extension settings and disabling the permission to read all sites, and then enabling the permission on only the ones that work/you need.

Giving me an example of website that doesn't work would be pretty helpful though, especially if it doesn't use javascript to play audio (spotify and netflix are already known to not work, for example), so that I can try troubleshooting.

Unfortunately the firefox extension API has some missing functions relative to chrome (probably for privacy's sake, so you can't just possibly tunnel all the audio coming from the browser to some 3rd party server etc.). That's why most, if not all audio boost extensions, don't work on websites like that.

**Comment by jwexus** [comment]
![2](https://github.com/user-attachments/assets/d0c4e4e4-4b12-46e3-bd4c-0cc54a725283)
oh it happened here too xD

**Comment by zWolfrost** [comment]
About tiktok, you're right, it should work there. In fact, I think I managed to fix it after a little troubleshooting. I would be really happy if you could test this new version on tiktok (and other website that do the same, as I don't know if it's just a tiktok-specific fix, and I don't know any other websites that don't play media at all).

You can download the new version in this zip file. Then, after you extracted it, to load it you can do: Manage Extension > Debug Add-ons > Load Temporary Add-on > Select "manifest.json" in the extracted folder.

When you go on tiktok, check the "Send cookies" checkbox in the pop-up and let me know if it works.

About the error in this very github page, I don't really know why that happened. For me, that video works fine and I can't manage to reproduce your error :P

[better_volume_booster-1.11.2.zip](https://github.com/user-attachments/files/16936401/better_volume_booster-1.11.2.zip)

**Comment by jwexus** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/f2f57183-43c6-4645-9314-252540cf4989)
maybe the same solution fixed it for the other problem too. tiktok works fine with the "send cookies" pop up and the other site works fine that had the same error that was in github. 

https://github.com/user-attachments/assets/262fb2a1-90fa-4177-bee0-42a2c1e2d757

**Comment by zWolfrost** [comment]
I'm happy to hear that. I will release this fix in the near future, maybe with some improvements.

**Comment by jwexus** [comment]
im glad! its an excellent extension btw. my fav so far so im actually happy

**Comment by jwexus** [comment]
im glad! its an excellent extension btw. my fav so far so im actually happy

**Comment by zWolfrost** [comment]
Just for the record, to access the "send cookies" button in the just released version you need to go into the options and set "Send cookies in media requests" to "ask" (I figured always showing it would get annoying for people who don't want to use it)
